name: nether-raids
version: '1.0.0'
main: me.lyn1.netherRaids.NetherRaids
api-version: '1.21'
load: STARTUP
authors: [ lynzl ]
description: minecraf plugin for nether raids
commands:
  netherraid:
    description: Starts a Nether mob raid.
    usage: /netherraid <difficulty> <number of waves> <radius>
    permission: netherraids.start
    permission-message: You do not have permission to start a Nether raid.
  endnetherraid:
    description: Ends an active Nether mob raid at your location.
    usage: /endnetherraid
    permission: netherraids.end
    permission-message: You do not have permission to end a Nether raid.
